databases:
  - name: furima-39987_production
    databaseName: furima-39987
    user: daiju ayaka
    region: singapore

services:
  - type: web
    name: daiju ayaka
    env: ruby
    region: singapore
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: <%= ENV['DATABASE_URL'] %>
        fromDatabase:
          name: render_app
          property: connectionString
      - key: <%= ENV['RAILS_MASTER_KEY'] %>
        sync: false
